---
# Ensure a Kubernetes node is cordoned (unschedulable).
- name: Cordon {{ kube_node_name | default(inventory_hostname) }}
  community.kubernetes.k8s_cordon:
    name: "{{ kube_node_name | default(inventory_hostname) }}"
    state: cordoned
    kubeconfig: "{{ kube_kubectl_delegate_kubeconfig_path }}"
  delegate_to: localhost

- name: Update cached cordon status for {{ kube_node_name | default(inventory_hostname) }}
  ansible.builtin.set_fact:
    kube_node_is_cordoned: true
