---
# Mark a Kubernetes node as schedulable again.
- name: Uncordon {{ kube_node_name | default(inventory_hostname) }}
  community.kubernetes.k8s_cordon:
    name: "{{ kube_node_name | default(inventory_hostname) }}"
    state: uncordoned
    kubeconfig: "{{ kube_kubectl_delegate_kubeconfig_path }}"
  delegate_to: localhost

- name: Update cached cordon status for {{ kube_node_name | default(inventory_hostname) }}
  ansible.builtin.set_fact:
    kube_node_is_cordoned: false
