---
- name: Check for available system updates
  ansible.builtin.command:
    argv:
      - dnf
      - -q
      - check-update
  register: dnf_check_result
  changed_when: false
  failed_when: dnf_check_result.rc not in [0, 100]

- name: Apply system updates
  when: dnf_check_result.rc == 100
  ansible.builtin.command:
    argv:
      - dnf
      - -y
      - upgrade
  register: dnf_upgrade_result
  changed_when: true
  failed_when: dnf_upgrade_result.rc != 0
