---
- name: Run Puppet agent
  ansible.builtin.command:
    argv:
      - puppet
      - agent
      - --test
  register: puppet_agent_result
  changed_when: puppet_agent_result.rc == 2
  failed_when: puppet_agent_result.rc not in [0, 2]
