---
- name: Reboot node
  ansible.builtin.reboot:
    reboot_command: shutdown -r now
    connect_timeout: 30
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Wait for Kubernetes API to respond after reboot
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Namespace
    name: default
    kubeconfig: "{{ kube_kubectl_delegate_kubeconfig_path }}"
  delegate_to: localhost
  register: kube_api_readiness_check
  retries: 60
  delay: 5
  until: (kube_api_readiness_check.resources | default([])) | length > 0
  changed_when: false
