---
- name: Gather RKE2 service facts before restart
  ansible.builtin.import_tasks: rke2_service_facts.yml

- name: Restart RKE2 service
  ansible.builtin.service:
    name: "{{ rke2_service_name }}"
    state: restarted
