all:
  children:
    kube_alpha:
      hosts:
        kube01:
          control_plane: true
        kube02:
          control_plane: true
        kube03:
          control_plane: true
        kube04:
        kube05:
    kube_bravo:
      hosts:
        kube06:
          control_plane: true
        kube07:
          control_plane: true
        kube08:
          control_plane: true
        kube09:
        kube10:
