[kube_alpha]
kube01 controlplane=true
kube02 controlplane=true
kube03 controlplane=true
kube04
kube05

[kube_bravo]
kube06 controlplane=true
kube07 controlplane=true
kube08 controlplane=true
kube09
kube10

[kube_charlie]
kube11 controlplane=true
kube12 controlplane=true
kube13 controlplane=true
kube14
kube15

[kube_delta]
kube16 controlplane=true
kube17 controlplane=true
kube18 controlplane=true
kube19
kube20

[kube_echo]
kube21 controlplane=true
kube22 controlplane=true
kube23 controlplane=true
kube24
kube25

[kube_foxtrot]
kube26 controlplane=true
kube27 controlplane=true
kube28 controlplane=true
kube29
kube30

[kube_golf]
kube31 controlplane=true
kube32 controlplane=true
kube33 controlplane=true
kube34
kube35

[kube_hotel]
kube36 controlplane=true
kube37 controlplane=true
kube38 controlplane=true
kube39
kube40

[kube_india]
kube41 controlplane=true
kube42 controlplane=true
kube43 controlplane=true
kube44
kube45

[kube_juliett]
kube46 controlplane=true
kube47 controlplane=true
kube48 controlplane=true
kube49
kube50
