---
all:
  children:
    kube_alpha:
      vars:
        kube_cluster: kube_alpha
        kube_server_group: server
      children:
        server:
          hosts:
            "kube[01:03]":
        agent:
          hosts:
            "kube[04:05]":
    kube_bravo:
      vars:
        kube_cluster: kube_bravo
        kube_server_group: server
      children:
        server:
          hosts:
            "kube[06:08]":
        agent:
          hosts:
            "kube[09:10]":
    kube_charlie:
      vars:
        kube_cluster: kube_charlie
        kube_server_group: server
      children:
        server:
          hosts:
            "kube[11:13]":
        agent:
          hosts:
            "kube[14:15]":
